<?php

error_reporting(E_ALL);
ini_set('display_errors', '1');

// Set flag that this is a parent file
define( '_STS_INCLUDE', 1 );

// Avoid getting timed out
define( '_STS_SESSION_AJAX', 1 );

if( (isset($_GET['code']) && $_GET['code'] == "875406") ||
	(isset($_POST['code']) && $_POST['code'] == "875406") ) {
		
	if( isset($_GET['info']) ) {
		phpinfo();
		die;
	}
	

	// Set flag that this is an installer
	define( '_STS_INSTALL', 1 );

	require_once( "include/sts_config.php" );
	$sts_debug = isset($_GET['debug']);
	
	if(isset($_GET['mysql']) ) {
		$sts_subtitle = "MySQL Configuration";
		require_once( "include/header_inc.php" );
		echo '<div class="container" role="main">
		<h3>MySQL Configuration Suggestions</h3>
		<p>These are based on experience, to make Exspeedite run smoothly. They go in the my.ini file, most likely in <strong>C:\ProgramData\MySQL\MySQL Server 8.0\my.ini</strong></p>
		<p>Make sure the my.ini file is in ASCII format, or mysqld won\'t start.</p>
		<p>Once you made the changes, re-start the MySQL service. You don\'t need to re-start apache.</p>
		<pre>
innodb_buffer_pool_size = 4G
innodb_buffer_pool_instances = 16

innodb_io_capacity = 2000
innodb_read_io_threads = 64
innodb_thread_concurrency = 0
innodb_write_io_threads = 64

join_buffer_size = 1M
sort_buffer_size = 1M
		</pre>
		<h3><a class="btn btn-md btn-default" href="exp_install.php?code=875406"><span class="glyphicon glyphicon-ok"></span> Go back</a></h3>
		';
		die;
	}

	if( isset($_GET['CREATESCHEMA']) ) {
		echo "<h3>Creating schema ".$sts_database."</h3>";
		$result = new mysqli($sts_db_host, $sts_username, $sts_password, "");
		if( $result->connect_errno == 0 ) {
			$result1 = $result->query("CREATE SCHEMA `".$sts_database."` DEFAULT CHARACTER SET utf8");
		}
	}

	$sts_subtitle = "Install Exspeedite";
	require_once( "include/header_inc.php" );
	?>
	<!-- Fixed navbar -->
	<div class="navbar navbar-default navbar-fixed-top" role="navigation">
		<div class="container">
			<div class="navbar-header">
				<a class="navbar-brand" style="padding: 0px;" href="exp_install"><img src="images/EXSPEEDITEsmr.png" alt="<?php echo $sts_title ?>"></a>
			</div>
		</div>
	</div>
	
	<div class="container" role="main">
	
	<?php
	echo '<div class="panel panel-danger">
  <div class="panel-heading">
    <h3 class="panel-title">HOST = <strong>'.$_SERVER["HTTP_HOST"].'</strong>
    &nbsp;&nbsp;<span class="glyphicon glyphicon-arrow-right"></span>&nbsp;&nbsp;ROOT = <strong>'.$_SERVER["CONTEXT_DOCUMENT_ROOT"].'</strong>
    &nbsp;&nbsp;SCRIPT = <strong>'.$_SERVER["SCRIPT_FILENAME"].'</strong>
    </h3>
  </div>
  <div class="panel-body">	
	<p>IF THE URL YOU ENTERED GOES TO THE WRONG DIRECTORY LISTED ABOVE, DO NOT PRESS BUTTONS BELOW. FIRST FIX YOUR APACHE VIRTUAL HOSTS CONFIGURATION</p>
	 </div>
</div>';



		$dirs = explode('/',$_SERVER['REQUEST_URI']);
		array_pop( $dirs );
		if( $dirs[0] == '' ) array_shift($dirs);
		array_unshift( $dirs, $_SERVER['HTTP_HOST'] );
		
		//echo "<p>dirs = </p>
		//<pre>";
		//var_dump($dirs);
		//echo "</pre>";
		$path = "http://" . implode('/', $dirs);
		//echo "<p>PATH = $path</p>";
		$dir = $_SERVER["CONTEXT_DOCUMENT_ROOT"];
		
		if( isset($_POST['DB_HOST']) ) { //! Write the config file
			if( substr($_POST['EXP_ROOT'], -1) == '/' )
				$_POST['EXP_ROOT'] = rtrim($_POST['EXP_ROOT'],'/');
			if( substr($_POST['EXP_DIR'], -1) <> '/' )
				$_POST['EXP_DIR'] = $_POST['EXP_DIR'].'/';
		
			//! SCR# 788 - New config subdirectories
			$subdomain = explode('.', $_SERVER["HTTP_HOST"])[0];
			$config_dir = $_POST['EXP_DIR']."include";
			if( file_exists($config_dir) && is_dir($config_dir) ) {
				if( file_exists($config_dir.DIRECTORY_SEPARATOR.$subdomain ) ) {
					$config_dir = $config_dir.DIRECTORY_SEPARATOR.$subdomain;
				} else if( is_writeable($config_dir) ) {
					mkdir($config_dir.DIRECTORY_SEPARATOR.$subdomain);
					$config_dir = $config_dir.DIRECTORY_SEPARATOR.$subdomain;
				}

				$config_file_contents = "<?php
	
	// no direct access
	defined('_STS_INCLUDE') or die('Restricted access');
			
	// Generated by exp_install.php ".date('l jS \of F Y h:i:s A')."
	// Stored in ".$config_dir.DIRECTORY_SEPARATOR.EXP_CONFIG_FILE."
	
	\$sts_crm_timezone = \"".$_POST['EXP_TIMEZONE']."\";
	\$sts_crm_root = \"".$_POST['EXP_ROOT']."\";
	\$sts_crm_dir = \"".$_POST['EXP_DIR']."\";
	
	\$sts_db_host	= \"".$_POST['DB_HOST']."\";
	\$sts_db_port	= \"".$_POST['DB_PORT']."\";
	\$sts_username	= \"".$_POST['DB_USER']."\";
	\$sts_password	= \"".$_POST['DB_PASSWORD']."\";
	\$sts_database	= \"".$_POST['DB_DATABASE']."\";
	
	?>";
				if( ! is_writeable($config_dir) ) {
					echo "<h2><strong>Error:</strong> unable to write config file - directory $config_dir is READ-ONLY</h2>
					<p>Check your directory permissions or directory ownership</p>";
				} else if( ! file_put_contents($config_dir.DIRECTORY_SEPARATOR.EXP_CONFIG_FILE, $config_file_contents) ) {
					echo "<h2><strong>Error:</strong> unable to write config file ".$config_dir.DIRECTORY_SEPARATOR.EXP_CONFIG_FILE."</h2>
					<p>Check your file and directory permissions or file ownership</p>";
				} else {
					echo "<h2><strong>Step 1:</strong> wrote config file ".$config_dir.DIRECTORY_SEPARATOR.EXP_CONFIG_FILE."</h2>";
					echo '<h3><a class="btn btn-md btn-default" href="exp_install.php?code=875406"><span class="glyphicon glyphicon-ok"></span> Go back</a>';
					if( isset($_POST['EXP_ADMIN']) && $_POST['EXP_ADMIN'] <> '' &&
						isset($_POST['EXP_EMAIL']) && $_POST['EXP_EMAIL'] <> '' &&
						isset($_POST['EXP_PASSWORD']) && $_POST['EXP_PASSWORD'] <> '' )
						echo '<h3><a class="btn btn-md btn-success inform" href="exp_install.php?code=875406&STEP2&EXP_ADMIN='.urlencode($_POST['EXP_ADMIN']).'&EXP_EMAIL='.urlencode($_POST['EXP_EMAIL']).'&EXP_PASSWORD='.urlencode($_POST['EXP_PASSWORD']).'" data-toggle="popover" data-placement="bottom" data-content="Create admin user.<br><strong>Only needed for new installs.</strong>"><span class="glyphicon glyphicon-user"></span> Step 2</a> Create Admin User';
					echo '</h3>';
				}

			} else {
				echo "<h2><strong>Error:</strong> directory $config_dir is MISSING</h2>
				<p>Check your directory setup</p>";
			}
			
			
		} else if( isset($_GET['STEP2']) &&
			isset($_GET['EXP_ADMIN']) && $_GET['EXP_ADMIN'] <> '' &&
			isset($_GET['EXP_EMAIL']) && $_GET['EXP_EMAIL'] <> '' &&
			isset($_GET['EXP_PASSWORD']) && $_GET['EXP_PASSWORD'] <> '' ) {
			try {
				require_once( "include/sts_user_class.php" );
			} catch (Exception $e) {
				echo "<p><strong>Caught exception:</strong> ".  $e->getMessage()."</p>
				<div class=\"well well-md\">
				<p>Double check:</p>
				<ol>
				<li><p>The database server is listening on <strong>$sts_db_host</strong> port <strong>$sts_db_port</strong></p>
				<p>If you see \"Access denied\" then likely the server is running.</li>
				<li><p>The database/schema <strong>$sts_database</strong> exists.</p></li>
				<li><p>The user <strong>$sts_username</strong> exists with the correct password.</p>
				<p>If the user is missing, try the following:</p>
				<p>CREATE USER '$sts_username'@'$sts_db_host' IDENTIFIED BY 'PASSWORD';</p></li>
				<li><p>The user <strong>$sts_username</strong> has rights to <strong>$sts_database</strong></p>
				<p>If the user exists try the following:</p>
				<p>GRANT ALL PRIVILEGES ON $sts_database . * TO '$sts_username'@'$sts_db_host';<br>
				FLUSH PRIVILEGES;</p></li>
				</ol>
				</div>";
				die;
			}
			$user_table = new sts_user($exspeedite_db, $sts_debug);

			$result = $user_table->fetch_rows("USERNAME = '".$_GET['EXP_ADMIN']."'");
			
			if( $result ) {
				echo "<h2><strong>Step 2:</strong> Admin user exists ".$_GET['EXP_ADMIN']."</h2>";
			} else {
				$result = $user_table->add( array( "USERNAME" => $_GET['EXP_ADMIN'],
					"USER_PASSWORD" => $_GET['EXP_PASSWORD'], "USER_GROUPS" => "admin,user",
					"FULLNAME" => "Admin User", "EMAIL" => $_GET['EXP_EMAIL'] ) );
				echo "<h2><strong>Step 2:</strong> created admin user ".$_GET['EXP_ADMIN']."</h2>";
			}
			echo '<a class="btn btn-md btn-success" href="exp_login.php"><span class="glyphicon glyphicon-ok"></span> Go to login screen</a>';
			
		} else {
			$subdomain = explode('.', $_SERVER["HTTP_HOST"])[0];
			$config_dir = (isset($sts_crm_dir) ? $sts_crm_dir : $dir)."include";
			if( file_exists($config_dir) ) {
				if( file_exists($config_dir.DIRECTORY_SEPARATOR.$subdomain ) ) {
					$config_dir = $config_dir.DIRECTORY_SEPARATOR.$subdomain;
				}
			}
			
			$config_exists =  file_exists($config_dir.DIRECTORY_SEPARATOR.EXP_CONFIG_FILE);
	?>
	
		<form role="form" class="form-horizontal" action="exp_install.php" 
					method="post" enctype="multipart/form-data" 
					name="install" id="install">
			<input name="code" type="hidden" value="875406">
			<div class="well well-lg">
				<div class="form-group">
					<div class="col-sm-4">
						<h2 class="text-center">MySQL Database</h2>
						<div class="form-group">
							<label for="DB_HOST" class="col-sm-4 control-label">Hostname</label>
							<div class="col-sm-8">
								<input class="form-control" name="DB_HOST" id="DB_HOST" type="text"
									placeholder="Hostname" value="<?php echo $config_exists && isset($sts_db_host) ? $sts_db_host : "localhost"; ?>" >
							</div>
						</div>
						<div class="form-group">
							<label for="DB_PORT" class="col-sm-4 control-label">Port</label>
							<div class="col-sm-8">
								<input class="form-control" name="DB_PORT" id="DB_PORT" type="text"
									placeholder="Port" value="<?php echo $config_exists && isset($sts_db_port) ? $sts_db_port : "3306"; ?>" >
							</div>
						</div>
						<div class="form-group">
							<label for="DB_USER" class="col-sm-4 control-label">Username</label>
							<div class="col-sm-8">
								<input class="form-control" name="DB_USER" id="DB_USER" type="text"
									placeholder="Username" <?php echo $config_exists ? 'value="'.$sts_username.'"' : ""; ?>>
							</div>
						</div>
						<div class="form-group">
							<label for="DB_PASSWORD" class="col-sm-4 control-label">Password</label>
							<div class="col-sm-8">
								<input class="form-control" name="DB_PASSWORD" id="DB_PASSWORD" type="text"
									placeholder="Password" <?php echo $config_exists ? 'value="'.$sts_password.'"' : ""; ?>>
							</div>
						</div>
						<div class="form-group">
							<label for="DB_DATABASE" class="col-sm-4 control-label">Database</label>
							<div class="col-sm-8">
								<input class="form-control" name="DB_DATABASE" id="DB_DATABASE" type="text"
									placeholder="Database" <?php echo $config_exists ? 'value="'.$sts_database.'"' : ""; ?>>
							</div>
						</div>
					</div>
					<div class="col-sm-8">
						<h2 class="text-center">Exspeedite Settings</h2>
						<div class="form-group">
							<label for="EXP_ROOT" class="col-sm-4 control-label">Time Zone</label>
							<div class="col-sm-8">
								<input class="form-control" name="EXP_TIMEZONE" id="EXP_TIMEZONE" type="text"
									placeholder="Time Zone" value="<?php echo isset($sts_crm_timezone) ? $sts_crm_timezone : 'America/Chicago'; ?>">
								<code><strong><span class="text-warning glyphicon glyphicon-warning-sign"></span></strong> Must be in <a href="http://us3.php.net/manual/en/timezones.php" target="_blank">this format</a></code>
							</div>
						</div>
						<div class="form-group">
							<label for="EXP_ROOT" class="col-sm-4 control-label">Root Path</label>
							<div class="col-sm-8">
								<input class="form-control" name="EXP_ROOT" id="EXP_ROOT" type="text"
									placeholder="Path to Exspeedite" value="<?php echo isset($sts_crm_root) ? $sts_crm_root : $path; ?>">
								<code><strong><span class="text-warning glyphicon glyphicon-warning-sign"></span></strong> Do not end with a slash</code>
							</div>
						</div>
						<div class="form-group">
							<label for="EXP_DIR" class="col-sm-4 control-label">Root Directory</label>
							<div class="col-sm-8">
								<input class="form-control" name="EXP_DIR" id="EXP_DIR" type="text"
									placeholder="Directory to Exspeedite" value="<?php echo isset($sts_crm_dir) ? $sts_crm_dir : $dir; ?>">
								<code><strong><span class="text-warning glyphicon glyphicon-warning-sign"></span></strong> Use forward slashes, end with a slash</code>
							</div>
						</div>
						<div class="form-group">
							<label for="EXP_ADMIN" class="col-sm-4 control-label">Admin User</label>
							<div class="col-sm-8">
								<input class="form-control" name="EXP_ADMIN" id="EXP_ADMIN" type="text"
									placeholder="Username" >
							</div>
						</div>
						<div class="form-group">
							<label for="EXP_EMAIL" class="col-sm-4 control-label">Admin Email</label>
							<div class="col-sm-8">
								<input class="form-control" name="EXP_EMAIL" id="EXP_EMAIL" type="text"
									placeholder="Email address" >
							</div>
						</div>
						<div class="form-group">
							<label for="EXP_PASSWORD" class="col-sm-4 control-label">Admin Password</label>
							<div class="col-sm-8">
								<input class="form-control" name="EXP_PASSWORD" id="EXP_PASSWORD" type="text"
									placeholder="Password" >
							</div>
						</div>
					</div>
				</div>
				<div class="form-group">
					<h4>
					<div class="btn-group">
						<a class="btn btn-md btn-default inform" href="exp_install.php?code=875406&info" id="PHP_INFO" data-toggle="popover" data-content="Check the installed PHP version information."><span class="glyphicon glyphicon-search"></span> Check PHP</a>
						<a class="btn btn-md btn-default inform" href="exp_install.php?code=875406&mysql" id="MYSQL_INFO" data-toggle="popover" data-content="Tips on configuring MySQL."><span class="glyphicon glyphicon-info-sign"></span> MySQL Config</a>
						<a class="btn btn-md btn-default inform" href="#" id="CHECK_DB" data-toggle="popover" data-content="Try to connect to the<br>database with these settings."><span class="glyphicon glyphicon-search"></span> Check DB</a>
						<a class="btn btn-md btn-default inform" href="exp_repair_db.php?CHECK_SCHEMA" id="CHECK_SCHEMA" data-toggle="popover" data-content="Check the schema for updates and get a patch."><span class="glyphicon glyphicon-search"></span> Check Schema</a>
						<a class="btn btn-md btn-warning inform" href="#" id="UPDATE_PATHS" data-toggle="popover" data-content="Update the paths in scripts,<br>based upon root directory.<br><strong>Do this every upgrade</strong>"><span class="glyphicon glyphicon-wrench"></span> Update Paths</a>
						<button class="btn btn-md btn-success inform" name="save" type="submit" data-toggle="popover" data-content="Save the settings to the config file.<br><strong>Only needed for new installs or if you changed something above.</strong>"><span class="glyphicon glyphicon-floppy-disk"></span> Save Config</button> <br>
						<?php
						//! Display config file
						if( $config_exists )
							echo "Config file ".$config_dir.DIRECTORY_SEPARATOR.EXP_CONFIG_FILE." exists!";
						else if( ! file_exists($config_dir) )
							echo "Directory $config_dir missing!";
						else if( ! is_writable($config_dir) )
							echo "Directory $config_dir not writeable!";
						else
							echo "Config will be saved to ".$config_dir.DIRECTORY_SEPARATOR.EXP_CONFIG_FILE;
						?>
					</div>
					</h4>
				</div>
				<?php
				if( $config_exists ) {
					$string = file_get_contents($config_dir.DIRECTORY_SEPARATOR.EXP_CONFIG_FILE);
					echo "<pre><code>
".htmlspecialchars($string)."
</code></pre>";
				}
				?>
			</div>
		</form>
	</div>
	
		<div class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true" id="db_check_modal">
		  <div class="modal-dialog">
			<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				<h4 class="modal-title" id="myModalLabel"><span class="text-success"><strong>Checking DB Credentials...</strong></span></h4>
			</div>
			<div class="modal-body">
				<p class="text-center"><img src="images/loading.gif" alt="loading" width="125" height="125" /></p>
			</div>
			</div>
			</div>
		</div>
	
	
	<script language="JavaScript" type="text/javascript"><!--
		$(document).ready( function () {
			$('#CHECK_DB').on('click', function() {
				$('#db_check_modal').modal({
					container: 'body'
				});
				$('#myModalLabel').html('<span class="text-success"><strong>Checking DB Credentials...</strong></span>');
				$.getJSON( "exp_check_db.php?code=Honey&DB_HOST=" + encodeURIComponent($("#DB_HOST").val()) +
					"&DB_USER=" + encodeURIComponent($("#DB_USER").val()) +
					"&DB_PASSWORD=" + encodeURIComponent($("#DB_PASSWORD").val()) +
					"&DB_DATABASE=" + encodeURIComponent($("#DB_DATABASE").val()), function( data ) {
				if( data.errno == 0 )
					$( ".modal-body" ).html( '<h3>Successful DB Connection...<br>'+data.msg+'<br><br><button type="button" class="btn btn-md btn-default" data-dismiss="modal" aria-hidden="true">Close</button></h3>' );
				else if( data.errno == 1 )
					$( ".modal-body" ).html( '<h3>Failed DB Connection...<br>'+data.msg+'<br><br><a class="btn btn-md btn-danger" href="exp_install.php?code=875406&CREATESCHEMA">Create Schema</a> <button type="button" class="btn btn-md btn-default" data-dismiss="modal" aria-hidden="true">Close</button></h3>' );
				else
					$( ".modal-body" ).html( '<h3>Failed DB Connection...<br>'+data.msg+'<br><br><button type="button" class="btn btn-md btn-default" data-dismiss="modal" aria-hidden="true">Close</button></h3>' );
				});
				return false;
			});

			$('#UPDATE_PATHS').on('click', function() {
				$('#db_check_modal').modal({
					container: 'body'
				});
				$('#myModalLabel').html('<span class="text-success"><strong>Updating Paths...</strong></span>');
				$.get( "exp_update_paths.php?code=Graham", function( data ) {
				console.log(data);
				if( data )
					$( ".modal-body" ).html( '<h3>Successfully updated... <button type="button" class="btn btn-md btn-default" data-dismiss="modal" aria-hidden="true">Close</button></h3>' );
				else
					$( ".modal-body" ).html( '<h3>Failed to update... <button type="button" class="btn btn-md btn-default" data-dismiss="modal" aria-hidden="true">Close</button></h3>' );
				});
				return false;
			});
		});
	//--></script>

	
<?php
	}
	require_once( "include/footer_inc.php" );
}
?>
