--! SCR# 614 - This patch is necessary because the column names are the primary index
-- for CHECK_SCHEMA.
-- Run this BEFORE a CHECK_SCHEMA

use pipco1;

ALTER TABLE exp_attachment
CHANGE COLUMN `COMPRESSED` `IS_COMPRESSED` TINYINT(1) NOT NULL DEFAULT '0' ;

ALTER TABLE exp_business_code
CHANGE COLUMN `NAME` `BC_NAME` VARCHAR(20) NOT NULL,
CHANGE COLUMN `DESCRIPTION` `BC_DESCRIPTION` VARCHAR(90) NULL DEFAULT NULL ;

ALTER TABLE exp_canada_tax 
CHANGE COLUMN `NAME` `FULLNAME` VARCHAR(45) NOT NULL ;

ALTER TABLE exp_card_advance 
CHANGE COLUMN `SOURCE` `CARD_SOURCE` VARCHAR(45) NOT NULL ,
CHANGE COLUMN `STOP` `CARD_STOP` VARCHAR(15) NULL DEFAULT NULL ;

ALTER TABLE exp_carrier 
CHANGE COLUMN `NAME` `CARRIER_NAME` VARCHAR(40) NULL DEFAULT NULL,
CHANGE COLUMN `DELETED` `ISDELETED` TINYINT(1) NOT NULL DEFAULT '0' ;

ALTER TABLE exp_client 
CHANGE COLUMN `NAME` `CLIENT_NAME` VARCHAR(128) NULL DEFAULT NULL,
CHANGE COLUMN `DELETED` `ISDELETED` TINYINT(1) NOT NULL DEFAULT '0' ;

ALTER TABLE exp_commodity
CHANGE COLUMN `NAME` `COMMODITY_NAME` VARCHAR(20) NOT NULL ,
CHANGE COLUMN `DESCRIPTION` `COMMODITY_DESCRIPTION` VARCHAR(90) NULL DEFAULT NULL ;

ALTER TABLE exp_commodity_class 
CHANGE COLUMN `NAME` `CC_NAME` VARCHAR(10) NOT NULL COMMENT 'Name of commodity\\n' ,
CHANGE COLUMN `DESCRIPTION` `CC_DESCRIPTION` VARCHAR(90) NULL DEFAULT NULL ;

ALTER TABLE exp_company 
CHANGE COLUMN `NAME` `COMPANY_NAME` VARCHAR(255) NOT NULL ;

ALTER TABLE exp_contact_info 
CHANGE COLUMN `DELETED` `ISDELETED` TINYINT(1) NOT NULL DEFAULT '0' ;

ALTER TABLE exp_office 
CHANGE COLUMN `NAME` `OFFICE_NAME` VARCHAR(255) NOT NULL ;

ALTER TABLE exp_driver
CHANGE COLUMN `ACTIVE` `ISACTIVE` ENUM('Inactive', 'Active', 'OOS') NULL DEFAULT 'Active' COMMENT 'this will be whether the driver is actively still working at the company or not  AND DOES NOT SHOW US ANYWHERE EXCEPT IN SET IF INACTIVE' ,
CHANGE COLUMN `DELETED` `ISDELETED` TINYINT(1) NOT NULL DEFAULT '0' ;

ALTER TABLE exp_driver_card
CHANGE COLUMN `SOURCE` `CARD_SOURCE` VARCHAR(20) NOT NULL ;

ALTER TABLE exp_tractor_card 
CHANGE COLUMN `SOURCE` `CARD_SOURCE` VARCHAR(20) NOT NULL ;

ALTER TABLE exp_edi
CHANGE COLUMN `CLIENT` `EDI_CLIENT` VARCHAR(30) NULL DEFAULT NULL ;

ALTER TABLE exp_exchange
CHANGE COLUMN `SOURCE` `RATE_SOURCE` ENUM('bankofcanada.ca', 'Fixer.io', 'manual') NOT NULL ;

ALTER TABLE exp_fleet
CHANGE COLUMN `NAME` `FLEET_NAME` VARCHAR(128) NOT NULL ;

ALTER TABLE exp_insp_report 
CHANGE COLUMN `NAME` `REPORT_NAME` VARCHAR(128) NOT NULL DEFAULT 'Default' ;

ALTER TABLE exp_insp_report_item 
CHANGE COLUMN `SERIAL` `SERIAL_NUM` VARCHAR(40) NULL DEFAULT NULL ;

ALTER TABLE exp_insp_report_part 
CHANGE COLUMN `NAME` `PART_NAME` VARCHAR(45) NULL DEFAULT NULL ,
CHANGE COLUMN `DESCRIPTION` `PART_DESCRIPTION` VARCHAR(256) NULL DEFAULT NULL ;

ALTER TABLE exp_item_list 
CHANGE COLUMN `DESCRIPTION` `ITEM_DESCRIPTION` VARCHAR(255) NULL DEFAULT NULL ;

ALTER TABLE exp_osd 
CHANGE COLUMN `DESCRIPTION` `OSD_DESCRIPTION` VARCHAR(45) NULL DEFAULT NULL ;

ALTER TABLE exp_pallet 
CHANGE COLUMN `CLIENT` `PALLET_CLIENT` INT(11) NOT NULL ;

ALTER TABLE exp_report
CHANGE COLUMN `DESCRIPTION` `REPORT_DESCRIPTION` VARCHAR(200) NULL DEFAULT NULL ;

ALTER TABLE exp_video
CHANGE COLUMN `DESCRIPTION` `VIDEO_DESCRIPTION` VARCHAR(200) NULL DEFAULT NULL ;

ALTER TABLE exp_rm_class
CHANGE COLUMN `NAME` `CLASS_NAME` VARCHAR(128) NOT NULL ,
CHANGE COLUMN `DESCRIPTION` `CLASS_DESCRIPTION` VARCHAR(255) NULL DEFAULT NULL ;

ALTER TABLE exp_rm_form 
CHANGE COLUMN `NAME` `FORM_NAME` VARCHAR(128) NOT NULL ,
CHANGE COLUMN `DESCRIPTION` `FORM_DESCRIPTION` VARCHAR(255) NULL DEFAULT NULL ;

ALTER TABLE exp_scr
CHANGE COLUMN `CLIENT` `SCR_CLIENT` VARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL ,
CHANGE COLUMN `DESCRIPTION` `SCR_DESCRIPTION` MEDIUMTEXT CHARACTER SET 'utf8' NULL DEFAULT NULL ,
CHANGE COLUMN `COMPONENT` `SCR_COMPONENT` VARCHAR(128) CHARACTER SET 'utf8' NULL DEFAULT NULL ;

ALTER TABLE exp_scr_history
CHANGE COLUMN `STATUS` `SCR_STATUS` INT(11) NOT NULL ;

ALTER TABLE exp_setting
CHANGE COLUMN `COMMENT` `SETTING_COMMENT` VARCHAR(255) NOT NULL ;

ALTER TABLE exp_states
CHANGE COLUMN `name` `STATE_NAME` CHAR(40) NOT NULL ;

ALTER TABLE exp_status 
CHANGE COLUMN `SOURCE` `SOURCE_TYPE` ENUM('shipment', 'load', 'stop') NOT NULL ,
CHANGE COLUMN `STATUS` `STATUS_STATE` INT(11) NULL DEFAULT NULL ,
CHANGE COLUMN `STOP` `STATUS_STOP` INT(11) NULL DEFAULT NULL ;

ALTER TABLE exp_status_codes
CHANGE COLUMN `SOURCE` `SOURCE_TYPE` ENUM('shipment', 'load', 'stop', 'client', 'scr', 'shipment-bill') NOT NULL ,
CHANGE COLUMN `STATUS` `STATUS_STATE` VARCHAR(32) NOT NULL ,
CHANGE COLUMN `DESCRIPTION` `STATUS_DESCRIPTION` VARCHAR(90) NULL DEFAULT NULL ;

ALTER TABLE exp_tractor
CHANGE COLUMN `OWNER` `TRACTOR_OWNER` VARCHAR(20) NULL DEFAULT NULL ,
CHANGE COLUMN `CLASS` `TRACTOR_CLASS` VARCHAR(10) NULL DEFAULT NULL ,
CHANGE COLUMN `YEAR` `TRACTOR_YEAR` VARCHAR(4) NULL DEFAULT NULL ,
CHANGE COLUMN `STATUS` `TRACTOR_STATUS` VARCHAR(10) NULL DEFAULT NULL ,
CHANGE COLUMN `ENGINE` `TRACTOR_ENGINE` VARCHAR(20) NULL DEFAULT NULL ,
CHANGE COLUMN `ACTIVE` `ISACTIVE` ENUM('Inactive', 'Active', 'OOS') NULL DEFAULT 'Active',
CHANGE COLUMN `DELETED` `ISDELETED` TINYINT(1) NOT NULL DEFAULT '0' ;

ALTER TABLE exp_license
CHANGE COLUMN `DELETED` `ISDELETED` TINYINT(1) NOT NULL DEFAULT '0' ;

ALTER TABLE exp_client_cat_rate_master 
CHANGE COLUMN `DELETED` `ISDELETED` TINYINT(1) NOT NULL DEFAULT '0' ;

ALTER TABLE exp_driver_rates
CHANGE COLUMN `DELETED` `ISDELETED` TINYINT(1) NOT NULL DEFAULT '0' ;

ALTER TABLE exp_trailer 
CHANGE COLUMN `ACTIVE` `ISACTIVE` ENUM('Inactive', 'Active', 'OOS') NULL DEFAULT 'Active' COMMENT 'this will be whether the driver is actively still working at the company or not  AND DOES NOT SHOW US ANYWHERE EXCEPT IN SET IF INACTIVE' ,
CHANGE COLUMN `OWNER` `TRAILER_OWNER` VARCHAR(20) NULL DEFAULT NULL ,
CHANGE COLUMN `YEAR` `TRAILER_YEAR` VARCHAR(4) NULL DEFAULT NULL ,
CHANGE COLUMN `DESCRIPTION` `TRAILER_DESCRIPTION` VARCHAR(50) NULL DEFAULT NULL ,
CHANGE COLUMN `STATUS` `TRAILER_STATUS` VARCHAR(10) NULL DEFAULT NULL ,
CHANGE COLUMN `DELETED` `ISDELETED` TINYINT(1) NOT NULL DEFAULT '0' ;

ALTER TABLE exp_unit
CHANGE COLUMN `NAME` `UNIT_NAME` VARCHAR(20) NOT NULL COMMENT 'Name' ;

ALTER TABLE exp_un_number 
CHANGE COLUMN `DESCRIPTION` `UN_DESCRIPTION` VARCHAR(200) NOT NULL ;

ALTER TABLE exp_user
CHANGE COLUMN `PASSWORD` `USER_PASSWORD` VARCHAR(64) NOT NULL ,
CHANGE COLUMN `GROUPS` `USER_GROUPS` VARCHAR(128) NOT NULL ,
CHANGE COLUMN `ACTIVE` `ISACTIVE` ENUM('Inactive', 'Active', 'OOS') NOT NULL DEFAULT 'Active' ;

ALTER TABLE exp_user_log
CHANGE COLUMN `EVENT` `LOG_EVENT` ENUM('login', 'logout', 'admin', 'finance', 'sales', 'scr') NOT NULL ;

ALTER TABLE exp_zone_filter
CHANGE COLUMN `NAME` `ZF_NAME` VARCHAR(20) NOT NULL ;




